apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260621-155112-88zomcn5eycc-service
spec:
  selector:
    app: enterprise-system-20260621-155112-88zomcn5eycc
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
